# Generated by Django 3.0.8 on 2020-07-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astralwhale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
