# Generated by Django 3.0.8 on 2020-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astralwhale', '0002_auto_20200721_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
